service: scraper

provider:
  environment:
    ENV: ${self:provider.stage}
  name: aws
  region: us-east-1
  runtime: nodejs20.x
  stage: ${opt:stage, "dev"}

functions:
  test-scraper:
    memorySize: 256
    timeout: 60
    image:
      uri: 156041417839.dkr.ecr.us-east-1.amazonaws.com/property-scraper:latest
      command:
        - dist/index.handler
